
app = "pinduoduo-telegram-bot"

[build]
  image = "python:3.10-slim"

[env]
  PYTHONUNBUFFERED = "TRUE"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
